dist: xenial

language: node_js

node_js:
  - 10
  - 11
  - 12

before_script:
  - "sudo apt-get update"
  - "sudo apt-get install -y build-essential libgtk-3-dev libgirepository1.0-dev gobject-introspection xvfb"

script: xvfb-run npm test